services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    container_name: rediscontainer
    command: ["redis-server", "--appendonly", "yes"]

  

volumes:
  redis_data:
 